services:
  grader-backend:
    container_name: grader-backend
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - host.docker.internal:host-gateway
